#########################
# DESARROLLADOR
# RMPG - LUIS ANGEL VALLEJO PEREZ
#########################
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Objetivos")
        MainWindow.resize(300, 300)
        MainWindow.setMinimumSize(QtCore.QSize(0, 300))
        MainWindow.setMaximumSize(QtCore.QSize(300, 300))
        self.WPrincipal = QtWidgets.QWidget(MainWindow)
        self.WPrincipal.setMinimumSize(QtCore.QSize(300, 0))
        self.WPrincipal.setMaximumSize(QtCore.QSize(300, 16777215))
        self.WPrincipal.setStyleSheet("#WPrincipal{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#btn_Aceptar{\n"
"    background-color: rgb(230, 230, 230);\n"
"    border-radius: 10px;\n"
"    color: rgb(0, 0, 0);\n"
"    font-size:14px;\n"
"}\n"
"#btn_Aceptar::hover{\n"
"background-color: rgb(203, 203, 203);\n"
"}")
        self.WPrincipal.setObjectName("WPrincipal")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.WPrincipal)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.widget = QtWidgets.QWidget(self.WPrincipal)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 10, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_TextoAgregarObjetivo = QtWidgets.QLabel(self.widget)
        self.lbl_TextoAgregarObjetivo.setMinimumSize(QtCore.QSize(0, 30))
        self.lbl_TextoAgregarObjetivo.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_TextoAgregarObjetivo.setFont(font)
        self.lbl_TextoAgregarObjetivo.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_TextoAgregarObjetivo.setObjectName("lbl_TextoAgregarObjetivo")
        self.verticalLayout.addWidget(self.lbl_TextoAgregarObjetivo)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.WRB = QtWidgets.QWidget(self.widget_2)
        self.WRB.setMinimumSize(QtCore.QSize(0, 0))
        self.WRB.setObjectName("WRB")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.WRB)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RB_Agregar = QtWidgets.QRadioButton(self.WRB)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.RB_Agregar.setFont(font)
        self.RB_Agregar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RB_Agregar.setObjectName("RB_Agregar")
        self.horizontalLayout.addWidget(self.RB_Agregar)
        self.RB_Modificar = QtWidgets.QRadioButton(self.WRB)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.RB_Modificar.setFont(font)
        self.RB_Modificar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RB_Modificar.setObjectName("RB_Modificar")
        self.horizontalLayout.addWidget(self.RB_Modificar)
        self.RB_Eliminar = QtWidgets.QRadioButton(self.WRB)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.RB_Eliminar.setFont(font)
        self.RB_Eliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RB_Eliminar.setObjectName("RB_Eliminar")
        self.horizontalLayout.addWidget(self.RB_Eliminar)
        self.verticalLayout_3.addWidget(self.WRB)
        self.WContenidoObjetivos = QtWidgets.QWidget(self.widget_2)
        self.WContenidoObjetivos.setMinimumSize(QtCore.QSize(0, 140))
        self.WContenidoObjetivos.setMaximumSize(QtCore.QSize(16777215, 140))
        self.WContenidoObjetivos.setObjectName("WContenidoObjetivos")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.WContenidoObjetivos)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.CB_Sucursales = QtWidgets.QComboBox(self.WContenidoObjetivos)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.CB_Sucursales.setFont(font)
        self.CB_Sucursales.setObjectName("CB_Sucursales")
        self.verticalLayout_4.addWidget(self.CB_Sucursales)
        self.label = QtWidgets.QLabel(self.WContenidoObjetivos)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.LE_Sucursal = QtWidgets.QLineEdit(self.WContenidoObjetivos)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.LE_Sucursal.setFont(font)
        self.LE_Sucursal.setObjectName("LE_Sucursal")
        self.verticalLayout_4.addWidget(self.LE_Sucursal)
        self.label_2 = QtWidgets.QLabel(self.WContenidoObjetivos)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.LE_Objetivo = QtWidgets.QLineEdit(self.WContenidoObjetivos)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.LE_Objetivo.setFont(font)
        self.LE_Objetivo.setObjectName("LE_Objetivo")
        self.verticalLayout_4.addWidget(self.LE_Objetivo)
        self.verticalLayout_3.addWidget(self.WContenidoObjetivos)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_Aceptar = QtWidgets.QPushButton(self.widget_5)
        self.btn_Aceptar.setMinimumSize(QtCore.QSize(150, 25))
        self.btn_Aceptar.setMaximumSize(QtCore.QSize(150, 25))
        self.btn_Aceptar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Aceptar.setStyleSheet("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../PruebaPagos/comprobado.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_Aceptar.setIcon(icon)
        self.btn_Aceptar.setObjectName("btn_Aceptar")
        self.gridLayout.addWidget(self.btn_Aceptar, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.verticalLayout.addWidget(self.widget_2)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.WPrincipal)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Objetivos", "Objetivos"))
        self.lbl_TextoAgregarObjetivo.setText(_translate("Objetivos", "Agregar Objetivos"))
        self.RB_Agregar.setText(_translate("Objetivos", "Agregar"))
        self.RB_Modificar.setText(_translate("Objetivos", "Modificar"))
        self.RB_Eliminar.setText(_translate("Objetivos", "Eliminar"))
        self.label.setText(_translate("Objetivos", "Sucursal"))
        self.label_2.setText(_translate("Objetivos", "Objetivo"))
        self.btn_Aceptar.setText(_translate("Objetivos", "Aceptar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
