# Form implementation generated from reading ui file 'c:\Users\Angel Rodriguez\LUIS_ANGEL_VALLEJO\programakw\App\Front\ventanasui\inicio_sesion.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(282, 177)
        Form.setStyleSheet("#btn_aceptar_ingreso{\n"
"    background-color: rgb(76, 175, 80);\n"
"    border-radius: 12px;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#btn_aceptar_ingreso:hover{\n"
"    background-color: rgb(0, 194, 12);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(230, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.txt_usuario = QtWidgets.QLineEdit(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_usuario.setFont(font)
        self.txt_usuario.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_usuario.setObjectName("txt_usuario")
        self.verticalLayout.addWidget(self.txt_usuario)
        self.txt_usuarioPassword = QtWidgets.QLineEdit(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txt_usuarioPassword.setFont(font)
        self.txt_usuarioPassword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txt_usuarioPassword.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.txt_usuarioPassword.setObjectName("txt_usuarioPassword")
        self.verticalLayout.addWidget(self.txt_usuarioPassword)
        self.btn_aceptar_ingreso = QtWidgets.QPushButton(parent=self.widget_2)
        self.btn_aceptar_ingreso.setMinimumSize(QtCore.QSize(0, 31))
        font = QtGui.QFont()
        font.setFamily("New York")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_aceptar_ingreso.setFont(font)
        self.btn_aceptar_ingreso.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_aceptar_ingreso.setObjectName("btn_aceptar_ingreso")
        self.verticalLayout.addWidget(self.btn_aceptar_ingreso)
        self.horizontalLayout.addWidget(self.widget_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Inicio de Sesión"))
        self.txt_usuario.setPlaceholderText(_translate("Form", "Usuario"))
        self.txt_usuarioPassword.setPlaceholderText(_translate("Form", "Contraseña"))
        self.btn_aceptar_ingreso.setText(_translate("Form", "Aceptar"))
