# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'V_KWSonora.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Kenworth_Sonora(object):
    def setupUi(self, Kenworth_Sonora):
        Kenworth_Sonora.setObjectName("Kenworth_Sonora")
        Kenworth_Sonora.resize(800, 500)
        Kenworth_Sonora.setMinimumSize(QtCore.QSize(800, 500))
        Kenworth_Sonora.setMaximumSize(QtCore.QSize(800, 500))
        Kenworth_Sonora.setStyleSheet("[objectName^=\"W_\"]{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#btnSubir{\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius:8px;\n"
"}\n"
"#btnSubir::Hover{\n"
"background-color: rgb(209, 209, 209);\n"
"}\n"
"#btnEliminar{\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius:8px;\n"
"}\n"
"#btnEliminar::Hover{\n"
"background-color: rgb(209, 209, 209);\n"
"}\n"
"#btnComenzar{\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius:8px;\n"
"}\n"
"#btnComenzar::Hover{\n"
"background-color: rgb(209, 209, 209);\n"
"}\n"
"#btn_Procesados{\n"
"background-color: rgb(232, 232, 232);\n"
"}\n"
"#btn_Procesados::hover{\n"
"background-color: rgb(209, 209, 209);\n"
"}\n"
"#btn_Originales{\n"
"background-color: rgb(232, 232, 232);\n"
"}\n"
"#btn_Originales::hover{\n"
"background-color: rgb(209, 209, 209);\n"
"}\n"
"#btn_Errores{\n"
"background-color: rgb(232, 232, 232);\n"
"}\n"
"#btn_Errores::hover{\n"
"background-color: rgb(209, 209, 209);\n"
"}\n"
"#btnAyuda{\n"
"background-color: rgb(232, 232, 232);\n"
"border-radius:5px;\n"
"}\n"
"#btnAyuda::hover{\n"
"background-color: rgb(209, 209, 209);\n"
"}\n"
"#btnMinimizar{\n"
"background-color: transparent;\n"
"}\n"
"#btnCerrar{\n"
"background-color: transparent;\n"
"}\n"
"#menuBar{\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius: 10px;\n"
"border-top-right-radius: 10px;\n"
"}\n"
"\n"
"")
        self.W_Principal = QtWidgets.QWidget(Kenworth_Sonora)
        self.W_Principal.setMinimumSize(QtCore.QSize(800, 500))
        self.W_Principal.setMaximumSize(QtCore.QSize(800, 500))
        self.W_Principal.setObjectName("W_Principal")
        self.W_Cuerpo = QtWidgets.QWidget(self.W_Principal)
        self.W_Cuerpo.setGeometry(QtCore.QRect(0, 67, 800, 280))
        self.W_Cuerpo.setMinimumSize(QtCore.QSize(0, 280))
        self.W_Cuerpo.setMaximumSize(QtCore.QSize(16777215, 280))
        self.W_Cuerpo.setObjectName("W_Cuerpo")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.W_Cuerpo)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.W_Pie = QtWidgets.QWidget(self.W_Principal)
        self.W_Pie.setGeometry(QtCore.QRect(0, 370, 800, 100))
        self.W_Pie.setMinimumSize(QtCore.QSize(0, 100))
        self.W_Pie.setMaximumSize(QtCore.QSize(16777215, 100))
        self.W_Pie.setObjectName("W_Pie")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.W_Pie)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.W_Botones = QtWidgets.QWidget(self.W_Pie)
        self.W_Botones.setMinimumSize(QtCore.QSize(450, 0))
        self.W_Botones.setObjectName("W_Botones")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.W_Botones)
        self.verticalLayout_6.setContentsMargins(10, 0, 0, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.W_BotonesTrabajo = QtWidgets.QWidget(self.W_Botones)
        self.W_BotonesTrabajo.setMinimumSize(QtCore.QSize(0, 50))
        self.W_BotonesTrabajo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.W_BotonesTrabajo.setObjectName("W_BotonesTrabajo")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.W_BotonesTrabajo)
        self.horizontalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnSubir = QtWidgets.QPushButton(self.W_BotonesTrabajo)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnSubir.setFont(font)
        self.btnSubir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnSubir.setStyleSheet("")
        self.btnSubir.setObjectName("btnSubir")
        self.horizontalLayout_5.addWidget(self.btnSubir)
        self.btnEliminar = QtWidgets.QPushButton(self.W_BotonesTrabajo)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnEliminar.setFont(font)
        self.btnEliminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnEliminar.setStyleSheet("")
        self.btnEliminar.setObjectName("btnEliminar")
        self.horizontalLayout_5.addWidget(self.btnEliminar)
        self.btnComenzar = QtWidgets.QPushButton(self.W_BotonesTrabajo)
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.btnComenzar.setFont(font)
        self.btnComenzar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnComenzar.setStyleSheet("")
        self.btnComenzar.setObjectName("btnComenzar")
        self.horizontalLayout_5.addWidget(self.btnComenzar)
        self.verticalLayout_6.addWidget(self.W_BotonesTrabajo)
        self.W_BotonesRutas = QtWidgets.QWidget(self.W_Botones)
        self.W_BotonesRutas.setObjectName("W_BotonesRutas")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.W_BotonesRutas)
        self.horizontalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_Procesados = QtWidgets.QPushButton(self.W_BotonesRutas)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.btn_Procesados.setFont(font)
        self.btn_Procesados.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Procesados.setStyleSheet("")
        self.btn_Procesados.setObjectName("btn_Procesados")
        self.horizontalLayout_6.addWidget(self.btn_Procesados)
        self.btn_Originales = QtWidgets.QPushButton(self.W_BotonesRutas)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_Originales.setFont(font)
        self.btn_Originales.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Originales.setStyleSheet("")
        self.btn_Originales.setObjectName("btn_Originales")
        self.horizontalLayout_6.addWidget(self.btn_Originales)
        self.btn_Errores = QtWidgets.QPushButton(self.W_BotonesRutas)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_Errores.setFont(font)
        self.btn_Errores.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_Errores.setStyleSheet("")
        self.btn_Errores.setObjectName("btn_Errores")
        self.horizontalLayout_6.addWidget(self.btn_Errores)
        self.verticalLayout_6.addWidget(self.W_BotonesRutas)
        self.horizontalLayout_4.addWidget(self.W_Botones)
        self.W_TextoProceso = QtWidgets.QWidget(self.W_Pie)
        self.W_TextoProceso.setObjectName("W_TextoProceso")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.W_TextoProceso)
        self.verticalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_TrabajandoCon = QtWidgets.QLabel(self.W_TextoProceso)
        self.lbl_TrabajandoCon.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_TrabajandoCon.setFont(font)
        self.lbl_TrabajandoCon.setText("")
        self.lbl_TrabajandoCon.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_TrabajandoCon.setObjectName("lbl_TrabajandoCon")
        self.verticalLayout_5.addWidget(self.lbl_TrabajandoCon)
        self.lbl_NombreReporte = QtWidgets.QLabel(self.W_TextoProceso)
        self.lbl_NombreReporte.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_NombreReporte.setFont(font)
        self.lbl_NombreReporte.setText("")
        self.lbl_NombreReporte.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_NombreReporte.setObjectName("lbl_NombreReporte")
        self.verticalLayout_5.addWidget(self.lbl_NombreReporte)
        self.horizontalLayout_4.addWidget(self.W_TextoProceso)
        self.W_BotonAyuda = QtWidgets.QWidget(self.W_Pie)
        self.W_BotonAyuda.setMinimumSize(QtCore.QSize(60, 0))
        self.W_BotonAyuda.setMaximumSize(QtCore.QSize(60, 60))
        self.W_BotonAyuda.setObjectName("W_BotonAyuda")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.W_BotonAyuda)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.btnAyuda = QtWidgets.QPushButton(self.W_BotonAyuda)
        self.btnAyuda.setMaximumSize(QtCore.QSize(16777213, 16777215))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnAyuda.setFont(font)
        self.btnAyuda.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAyuda.setAcceptDrops(False)
        self.btnAyuda.setToolTip("<html><head/><body><p align=\"justify\">Ayuda</p></body></html>")
        self.btnAyuda.setToolTipDuration(0)
        self.btnAyuda.setStatusTip("")
        self.btnAyuda.setWhatsThis("")
        self.btnAyuda.setAccessibleName("")
        self.btnAyuda.setAccessibleDescription("")
        self.btnAyuda.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btnAyuda.setAutoFillBackground(False)
        self.btnAyuda.setStyleSheet("")
        self.btnAyuda.setLocale(QtCore.QLocale(QtCore.QLocale.Spanish, QtCore.QLocale.Nicaragua))
        self.btnAyuda.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Source/Icon_Help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAyuda.setIcon(icon)
        self.btnAyuda.setIconSize(QtCore.QSize(32, 32))
        self.btnAyuda.setObjectName("btnAyuda")
        self.verticalLayout_7.addWidget(self.btnAyuda)
        self.horizontalLayout_4.addWidget(self.W_BotonAyuda)
        self.W_Cabecera = QtWidgets.QWidget(self.W_Principal)
        self.W_Cabecera.setGeometry(QtCore.QRect(0, 0, 800, 50))
        self.W_Cabecera.setMinimumSize(QtCore.QSize(0, 50))
        self.W_Cabecera.setMaximumSize(QtCore.QSize(16777215, 50))
        self.W_Cabecera.setObjectName("W_Cabecera")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.W_Cabecera)
        self.horizontalLayout.setContentsMargins(5, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.W_Logo = QtWidgets.QWidget(self.W_Cabecera)
        self.W_Logo.setMinimumSize(QtCore.QSize(200, 0))
        self.W_Logo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.W_Logo.setObjectName("W_Logo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.W_Logo)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout.addWidget(self.W_Logo)
        self.lblLogoKWS = QtWidgets.QLabel(self.W_Principal)
        self.lblLogoKWS.setGeometry(QtCore.QRect(5, 6, 200, 50))
        self.lblLogoKWS.setText("")
        self.lblLogoKWS.setPixmap(QtGui.QPixmap("../Source/Logo_KWSonora.png"))
        self.lblLogoKWS.setScaledContents(True)
        self.lblLogoKWS.setObjectName("lblLogoKWS")
        self.W_BotonesSalida = QtWidgets.QWidget(self.W_Principal)
        self.W_BotonesSalida.setGeometry(QtCore.QRect(725, 6, 75, 50))
        self.W_BotonesSalida.setMinimumSize(QtCore.QSize(75, 0))
        self.W_BotonesSalida.setMaximumSize(QtCore.QSize(75, 16777215))
        self.W_BotonesSalida.setObjectName("W_BotonesSalida")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.W_BotonesSalida)
        self.horizontalLayout_2.setContentsMargins(0, 0, 5, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnMinimizar = QtWidgets.QPushButton(self.W_BotonesSalida)
        self.btnMinimizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMinimizar.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Source/Icon_Minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMinimizar.setIcon(icon1)
        self.btnMinimizar.setIconSize(QtCore.QSize(30, 30))
        self.btnMinimizar.setObjectName("btnMinimizar")
        self.horizontalLayout_2.addWidget(self.btnMinimizar)
        self.btnCerrar = QtWidgets.QPushButton(self.W_BotonesSalida)
        self.btnCerrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnCerrar.setMouseTracking(False)
        self.btnCerrar.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Source/Icon_Close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCerrar.setIcon(icon2)
        self.btnCerrar.setIconSize(QtCore.QSize(30, 30))
        self.btnCerrar.setObjectName("btnCerrar")
        self.horizontalLayout_2.addWidget(self.btnCerrar)
        self.W_TablaIzquierda = QtWidgets.QWidget(self.W_Principal)
        self.W_TablaIzquierda.setGeometry(QtCore.QRect(0, 73, 400, 280))
        self.W_TablaIzquierda.setObjectName("W_TablaIzquierda")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.W_TablaIzquierda)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.lblTextoEnCola = QtWidgets.QLabel(self.W_TablaIzquierda)
        self.lblTextoEnCola.setMinimumSize(QtCore.QSize(0, 20))
        self.lblTextoEnCola.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTextoEnCola.setFont(font)
        self.lblTextoEnCola.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTextoEnCola.setObjectName("lblTextoEnCola")
        self.verticalLayout_3.addWidget(self.lblTextoEnCola)
        self.TWCola = QtWidgets.QTableWidget(self.W_TablaIzquierda)
        self.TWCola.setObjectName("TWCola")
        self.TWCola.setColumnCount(0)
        self.TWCola.setRowCount(0)
        self.verticalLayout_3.addWidget(self.TWCola)
        self.W_TablaDerecha = QtWidgets.QWidget(self.W_Principal)
        self.W_TablaDerecha.setGeometry(QtCore.QRect(400, 73, 400, 280))
        self.W_TablaDerecha.setObjectName("W_TablaDerecha")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.W_TablaDerecha)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lblTextoProcesado = QtWidgets.QLabel(self.W_TablaDerecha)
        self.lblTextoProcesado.setMinimumSize(QtCore.QSize(0, 20))
        self.lblTextoProcesado.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblTextoProcesado.setFont(font)
        self.lblTextoProcesado.setAlignment(QtCore.Qt.AlignCenter)
        self.lblTextoProcesado.setObjectName("lblTextoProcesado")
        self.verticalLayout_4.addWidget(self.lblTextoProcesado)
        self.TWProcesado = QtWidgets.QTableWidget(self.W_TablaDerecha)
        self.TWProcesado.setObjectName("TWProcesado")
        self.TWProcesado.setColumnCount(0)
        self.TWProcesado.setRowCount(0)
        self.verticalLayout_4.addWidget(self.TWProcesado)
        Kenworth_Sonora.setCentralWidget(self.W_Principal)
        self.menuBar = QtWidgets.QMenuBar(Kenworth_Sonora)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.menuBar.setFont(font)
        self.menuBar.setObjectName("menuBar")
        self.menuOPCIONES = QtWidgets.QMenu(self.menuBar)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.menuOPCIONES.setFont(font)
        self.menuOPCIONES.setObjectName("menuOPCIONES")
        self.menuPagoClientes = QtWidgets.QMenu(self.menuOPCIONES)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.menuPagoClientes.setFont(font)
        self.menuPagoClientes.setObjectName("menuPagoClientes")
        Kenworth_Sonora.setMenuBar(self.menuBar)
        self.actionObjetivos_Mensuales = QtWidgets.QAction(Kenworth_Sonora)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.actionObjetivos_Mensuales.setFont(font)
        self.actionObjetivos_Mensuales.setObjectName("actionObjetivos_Mensuales")
        self.actionFechaMovimiento = QtWidgets.QAction(Kenworth_Sonora)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.actionFechaMovimiento.setFont(font)
        self.actionFechaMovimiento.setObjectName("actionFechaMovimiento")
        self.actionDirecciones_de_envio = QtWidgets.QAction(Kenworth_Sonora)
        self.actionDirecciones_de_envio.setObjectName("actionDirecciones_de_envio")
        self.menuPagoClientes.addAction(self.actionObjetivos_Mensuales)
        self.menuOPCIONES.addAction(self.menuPagoClientes.menuAction())
        self.menuOPCIONES.addAction(self.actionFechaMovimiento)
        self.menuOPCIONES.addAction(self.actionDirecciones_de_envio)
        self.menuBar.addAction(self.menuOPCIONES.menuAction())

        self.retranslateUi(Kenworth_Sonora)
        QtCore.QMetaObject.connectSlotsByName(Kenworth_Sonora)

    def retranslateUi(self, Kenworth_Sonora):
        _translate = QtCore.QCoreApplication.translate
        Kenworth_Sonora.setWindowTitle(_translate("Kenworth_Sonora", "KENWORTH SONORA"))
        self.btnSubir.setToolTip(_translate("Kenworth_Sonora", "<html><head/><body><p>Selecciona un archivo .xlsx</p></body></html>"))
        self.btnSubir.setText(_translate("Kenworth_Sonora", "Subir"))
        self.btnEliminar.setToolTip(_translate("Kenworth_Sonora", "<html><head/><body><p>Elimina los archivos procesados</p></body></html>"))
        self.btnEliminar.setText(_translate("Kenworth_Sonora", "Eliminar"))
        self.btnComenzar.setToolTip(_translate("Kenworth_Sonora", "<html><head/><body><p>Comenzar el proceso</p></body></html>"))
        self.btnComenzar.setText(_translate("Kenworth_Sonora", "Comenzar"))
        self.btn_Procesados.setToolTip(_translate("Kenworth_Sonora", "<html><head/><body><p>Ruta de archivos procesados</p></body></html>"))
        self.btn_Procesados.setText(_translate("Kenworth_Sonora", "Procesados"))
        self.btn_Originales.setToolTip(_translate("Kenworth_Sonora", "<html><head/><body><p>Ruta de archivos originales</p></body></html>"))
        self.btn_Originales.setText(_translate("Kenworth_Sonora", "Originales"))
        self.btn_Errores.setToolTip(_translate("Kenworth_Sonora", "<html><head/><body><p>Ruta de archivos erroneos</p></body></html>"))
        self.btn_Errores.setText(_translate("Kenworth_Sonora", "Erroneos"))
        self.btnMinimizar.setToolTip(_translate("Kenworth_Sonora", "Minimizar"))
        self.btnCerrar.setToolTip(_translate("Kenworth_Sonora", "Cerrar"))
        self.lblTextoEnCola.setText(_translate("Kenworth_Sonora", "Trabajos En Espera"))
        self.lblTextoProcesado.setText(_translate("Kenworth_Sonora", "Trabajos Realizados"))
        self.menuOPCIONES.setTitle(_translate("Kenworth_Sonora", "OPCIONES"))
        self.menuPagoClientes.setTitle(_translate("Kenworth_Sonora", "Pago Clientes"))
        self.actionObjetivos_Mensuales.setText(_translate("Kenworth_Sonora", "Objetivos Mensuales"))
        self.actionFechaMovimiento.setText(_translate("Kenworth_Sonora", "Fecha Movimiento"))
        self.actionDirecciones_de_envio.setText(_translate("Kenworth_Sonora", "Direcciones de envio"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Kenworth_Sonora = QtWidgets.QMainWindow()
    ui = Ui_Kenworth_Sonora()
    ui.setupUi(Kenworth_Sonora)
    Kenworth_Sonora.show()
    sys.exit(app.exec_())
