# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fecha.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_FechaMovimiento(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(300, 100)
        Form.setMinimumSize(QtCore.QSize(300, 100))
        Form.setMaximumSize(QtCore.QSize(300, 16777215))
        Form.setStyleSheet("#w_principal{\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.w_principal = QtWidgets.QWidget(Form)
        self.w_principal.setObjectName("w_principal")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.w_principal)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.date_edit_date_movement = QtWidgets.QDateEdit(self.w_principal)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(True)
        self.date_edit_date_movement.setFont(font)
        self.date_edit_date_movement.setAlignment(QtCore.Qt.AlignCenter)
        self.date_edit_date_movement.setReadOnly(False)
        self.date_edit_date_movement.setCalendarPopup(True)
        self.date_edit_date_movement.setDate(QtCore.QDate(2023, 1, 1))
        self.date_edit_date_movement.setObjectName("date_edit_date_movement")
        self.verticalLayout_2.addWidget(self.date_edit_date_movement)
        self.verticalLayout.addWidget(self.w_principal)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Formulario", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form_FechaMovimiento()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
